const VtexAppKey = 'vtexappkey-techdenalipartnerus-HPIPQB';
const VtexAppToken = 'IJZQFEZIPUCWQOTFRKKAVKDRBIPWSSOTIMWUQZRDDZSGEYRCDVYFXUNHDIKRKOYGPWMWAPWUZBPITWOGAZHHIXXNMLPBKEANTNVFNKBXCRCMUQZEONATAOXQPYFTABAG';
export { VtexAppKey, VtexAppToken };