const VtexAppKey = 'vtexappkey-techdenalipartnerus-HPIPQB';
const VtexAppToken = 'IJZQFEZIPUCWQOTFRKKAVKDRBIPWSSOTIMWUQZRDDZSGEYRCDVYFXUNHDIKRKOYGPWMWAPWUZBPITWOGAZHHIXXNMLPBKEANTNVFNKBXCRCMUQZEONATAOXQPYFTABAG';
module.exports = { VtexAppKey, VtexAppToken };
